# Generated by Django 4.2.30 on 2026-04-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='download_file',
        ),
    ]
